# Generated by Django 5.0.3 on 2024-04-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_product_cost_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='',
        ),
    ]
